I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 539, in script
    j "Oh iya, maaf ya."
Exception: Sayer 'j' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 539, in script
    j "Oh iya, maaf ya."
  File "C:\Michael\Kuliah\Tingkat 2\renpy-8.3.2-sdk\renpy\ast.py", line 2573, in execute
    Say.execute(self)
  File "C:\Michael\Kuliah\Tingkat 2\renpy-8.3.2-sdk\renpy\ast.py", line 575, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Michael\Kuliah\Tingkat 2\renpy-8.3.2-sdk\renpy\ast.py", line 464, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'j' is not defined.

Windows-10-10.0.22631 AMD64
Ren'Py 8.3.2.24090902
Version 1.0
Tue Dec 10 17:50:41 2024
